# Generated by Django 4.1.2 on 2022-12-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="dish",
        ),
        migrations.AddField(
            model_name="checkout",
            name="dishes",
            field=models.BooleanField(null=True),
        ),
    ]
