# Generated by Django 4.1.2 on 2022-12-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dishes_page", "0001_initial"),
        ("food_order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="dish",
        ),
        migrations.AddField(
            model_name="checkout",
            name="dish",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish",
                to="dishes_page.dish",
            ),
            preserve_default=False,
        ),
    ]
