# Generated by Django 4.1.2 on 2022-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoauth", "0002_userprofile_language_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
    ]
