# Generated by Django 4.1.2 on 2022-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoauth", "0002_alter_userprofile_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("uk", "Ukrainian"), ("en", "English")],
                default="en",
                max_length=2,
            ),
        ),
    ]
