# Generated by Django 4.1.2 on 2022-10-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoauth", "0003_alter_userprofile_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en-us", "English"), ("uk", "Ukrainian")],
                default="en-us",
                max_length=10,
            ),
        ),
    ]
