# Generated by Django 4.1.2 on 2022-11-01 20:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("djangoauth", "0004_alter_userprofile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[500, 300],
                upload_to="avatars/",
            ),
        ),
    ]
